/* automatically generated by rust-bindgen 0.69.4 */

pub const BLE_MAIN_SERVICE_LOCAL_NAME: &[u8; 9] = b"co2nsole\0";
pub const BLE_MAIN_SENSOR_SERVICE: &[u8; 37] = b"0000FFE0-0000-1000-8000-00805F9B34FB\0";
pub const BLE_MAIN_SENSOR_STREAM_CHAR: &[u8; 37] = b"0000FFE0-0000-1000-8000-00805F9B34FB\0";
pub const BLE_MAIN_SENSOR_ACTION_CHAR: &[u8; 37] = b"beb5483e-36e1-4688-b7f5-ea07361b26a8\0";
pub const BLE_MAIN_SENSOR_CALIBRATE_CO2: &[u8; 15] = b"CalibrateMhZ19\0";
pub const BLE_MAIN_SENSOR_CALIBRATE_TEMPERATURE: &[u8; 21] = b"CalibrateTemperature\0";
pub const BLE_MAIN_SENSOR_CALIBRATE_HUMIDITY: &[u8; 18] = b"CalibrateHumidity\0";
pub const BLE_WINDOW_SERVICE_LOCAL_NAME: &[u8; 16] = b"co2nsole window\0";
pub const BLE_WINDOW_SENSOR_SERVICE: &[u8; 37] = b"19B10000-E8F2-537E-4F6C-D104768A1214\0";
pub const BLE_WINDOW_SENSOR_READ_CHAR: &[u8; 37] = b"a3b27688-3b9e-4214-970c-3db5f14c5d2b\0";
